name: E2E Test Reports

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
      head-ref:
        required: true
        type: string
      run-e2e:
        required: true
        type: boolean
      has-files-requiring-all-checks:
        required: true
        type: boolean
      pr-merged:
        required: false
        type: boolean
        default: false
      pr-closed:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  merge-reports:
    name: Merge reports
    if: ${{ !cancelled() && inputs.run-e2e == true && inputs.has-files-requiring-all-checks == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/yarn-playwright-install
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge into HTML Report
        run: yarn playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_number }}-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14

  publish-report:
    name: Publish HTML report
    if: ${{ !cancelled() && inputs.run-e2e == true && inputs.has-files-requiring-all-checks == true }}
    needs: [merge-reports]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      HTML_REPORT_URL_PATH: reports/${{ inputs.head-ref }}/${{ github.run_id }}/${{ github.run_attempt }}
      BRANCH_REPORTS_DIR: reports/${{ inputs.head-ref }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          repository: calcom/test-results
          ref: gh-pages
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Check for workflow reports
        run: |
          if [ -z "$(ls -A $BRANCH_REPORTS_DIR)" ]; then
            echo "BRANCH_REPORTS_EXIST="false"" >> $GITHUB_ENV
          else
            echo "BRANCH_REPORTS_EXIST="true"" >> $GITHUB_ENV
          fi
      - name: Cleanup old HTML reports
        if: ${{ env.BRANCH_REPORTS_EXIST == 'true' }}
        timeout-minutes: 3
        run: |
          rm -rf $BRANCH_REPORTS_DIR
          git add .
          git commit -m "workflow: remove all reports for branch ${{ inputs.head-ref }}"
      - name: Download zipped HTML report
        uses: actions/download-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_number }}-${{ github.run_attempt }}
          path: ${{ env.HTML_REPORT_URL_PATH }}
      - name: Push HTML Report
        timeout-minutes: 3
        run: |
          git add .
          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"

          while true; do
            git pull --rebase
            if [ $? -ne 0 ]; then
              echo "Failed to rebase. Please review manually."
              exit 1
            fi

            git push
            if [ $? -eq 0 ]; then
              echo "Successfully pushed HTML report to repo."
              exit 0
            fi
          done
      - name: Output Report URL as Workflow Annotation
        id: url
        run: |
          FULL_HTML_REPORT_URL=https://calcom.github.io/test-results/$HTML_REPORT_URL_PATH
          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
          echo "link=$FULL_HTML_REPORT_URL" >> $GITHUB_OUTPUT
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ inputs.pr-number }}
          comment-author: "github-actions[bot]"
          body-includes: <!-- GENERATED-E2E-RESULTS -->
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ inputs.pr-number }}
          body: |
            <!-- GENERATED-E2E-RESULTS -->
            ## E2E results are ready!
            - [Workflow #${{ github.run_number }}.${{ github.run_attempt }} latest results](${{ steps.url.outputs.link }})
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- GENERATED-E2E-RESULTS -->
            ## E2E results are ready!
            - [Workflow #${{ github.run_number }}.${{ github.run_attempt }} latest results](${{ steps.url.outputs.link }})

  cleanup-report:
    name: Cleanup HTML report
    if: ${{ !cancelled() && inputs.run-e2e == true && (inputs.pr-merged == true || inputs.pr-closed == true) }}
    needs: [publish-report]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          repository: calcom/test-results
          ref: gh-pages
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Cleanup HTML reports on PR close/merge
        env:
          BRANCH_REPORTS_DIR: reports/${{ inputs.head-ref }}
        run: |
          if [ -d "$BRANCH_REPORTS_DIR" ]; then
            rm -rf "$BRANCH_REPORTS_DIR"
            git add .
            git commit -m "workflow: remove all reports for branch ${{ inputs.head-ref }} (PR closed/merged)"
            git push
          else
            echo "No reports found for branch ${{ inputs.head-ref }}. Nothing to clean up."
          fi
