name: E2E Tests (Consolidated)
on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
        description: 'Type of E2E test to run (core, embed, app-store, atoms, embed-react, api-v2)'
      timeout_minutes:
        required: false
        type: number
        default: 20
        description: 'Timeout in minutes'
      runner_spec:
        required: false
        type: string
        default: 'buildjet-4vcpu-ubuntu-2204'
        description: 'Runner specification'
      matrix_shards:
        required: false
        type: string
        default: '[]'
        description: 'JSON array of matrix shards (empty for no matrix)'

permissions:
  actions: write
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096
  ALLOWED_HOSTNAMES: ${{ vars.CI_ALLOWED_HOSTNAMES }}
  CALENDSO_ENCRYPTION_KEY: ${{ secrets.CI_CALENDSO_ENCRYPTION_KEY }}
  DAILY_API_KEY: ${{ secrets.CI_DAILY_API_KEY }}
  DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
  DATABASE_DIRECT_URL: ${{ secrets.CI_DATABASE_URL }}
  DATABASE_READ_URL: ${{ secrets.CI_DATABASE_URL }}
  DATABASE_WRITE_URL: ${{ secrets.CI_DATABASE_URL }}
  DEPLOYSENTINEL_API_KEY: ${{ secrets.DEPLOYSENTINEL_API_KEY }}
  E2E_TEST_APPLE_CALENDAR_EMAIL: ${{ secrets.E2E_TEST_APPLE_CALENDAR_EMAIL }}
  E2E_TEST_APPLE_CALENDAR_PASSWORD: ${{ secrets.E2E_TEST_APPLE_CALENDAR_PASSWORD }}
  E2E_TEST_MAILHOG_ENABLED: ${{ vars.E2E_TEST_MAILHOG_ENABLED }}
  E2E_TEST_CALCOM_QA_EMAIL: ${{ secrets.E2E_TEST_CALCOM_QA_EMAIL }}
  E2E_TEST_CALCOM_QA_PASSWORD: ${{ secrets.E2E_TEST_CALCOM_QA_PASSWORD }}
  E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS: ${{ secrets.E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS }}
  E2E_TEST_CALCOM_GCAL_KEYS: ${{ secrets.E2E_TEST_CALCOM_GCAL_KEYS }}
  GOOGLE_API_CREDENTIALS: ${{ secrets.CI_GOOGLE_API_CREDENTIALS }}
  EMAIL_SERVER_HOST: ${{ secrets.CI_EMAIL_SERVER_HOST }}
  EMAIL_SERVER_PORT: ${{ secrets.CI_EMAIL_SERVER_PORT }}
  EMAIL_SERVER_USER: ${{ secrets.CI_EMAIL_SERVER_USER }}
  EMAIL_SERVER_PASSWORD: ${{ secrets.CI_EMAIL_SERVER_PASSWORD}}
  GOOGLE_LOGIN_ENABLED: ${{ vars.CI_GOOGLE_LOGIN_ENABLED }}
  NEXTAUTH_SECRET: ${{ secrets.CI_NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.CI_NEXTAUTH_URL }}
  NEXT_PUBLIC_API_V2_URL: ${{ secrets.CI_NEXT_PUBLIC_API_V2_URL }}
  NEXT_PUBLIC_API_V2_ROOT_URL: ${{ secrets.CI_NEXT_PUBLIC_API_V2_ROOT_URL }}
  NEXT_PUBLIC_IS_E2E: ${{ vars.CI_NEXT_PUBLIC_IS_E2E }}
  NEXT_PUBLIC_ORG_SELF_SERVE_ENABLED: ${{ vars.CI_NEXT_PUBLIC_ORG_SELF_SERVE_ENABLED }}
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.CI_NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
  NEXT_PUBLIC_WEBAPP_URL: ${{ vars.CI_NEXT_PUBLIC_WEBAPP_URL }}
  NEXT_PUBLIC_WEBSITE_URL: ${{ vars.CI_NEXT_PUBLIC_WEBSITE_URL }}
  PAYMENT_FEE_FIXED: ${{ vars.CI_PAYMENT_FEE_FIXED }}
  PAYMENT_FEE_PERCENTAGE: ${{ vars.CI_PAYMENT_FEE_PERCENTAGE }}
  SAML_ADMINS: ${{ secrets.CI_SAML_ADMINS }}
  SAML_DATABASE_URL: ${{ secrets.CI_SAML_DATABASE_URL }}
  STRIPE_PRIVATE_KEY: ${{ secrets.CI_STRIPE_PRIVATE_KEY }}
  STRIPE_CLIENT_ID: ${{ secrets.CI_STRIPE_CLIENT_ID }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.CI_STRIPE_WEBHOOK_SECRET }}
  SENDGRID_API_KEY: ${{ secrets.CI_SENDGRID_API_KEY }}
  SENDGRID_EMAIL: ${{ secrets.CI_SENDGRID_EMAIL }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  API_KEY_PREFIX: ${{ secrets.CI_API_KEY_PREFIX }}
  API_PORT: ${{ vars.CI_API_V2_PORT }}
  CALCOM_LICENSE_KEY: ${{ secrets.CI_CALCOM_LICENSE_KEY }}
  IS_E2E: true
  REDIS_URL: "redis://localhost:6379"
  LINGO_DOT_DEV_API_KEY: ${{ secrets.CI_LINGO_DOT_DEV_API_KEY }}
  STRIPE_API_KEY: ${{ secrets.CI_STRIPE_PRIVATE_KEY }}
  SLOTS_CACHE_TTL: ${{ secrets.CI_SLOTS_CACHE_TTL }}
  ATOMS_E2E_OAUTH_CLIENT_ID: ${{ secrets.ATOMS_E2E_OAUTH_CLIENT_ID }}
  ATOMS_E2E_OAUTH_CLIENT_SECRET: ${{ secrets.ATOMS_E2E_OAUTH_CLIENT_SECRET }}
  ATOMS_E2E_API_URL: ${{ secrets.ATOMS_E2E_API_URL }}
  ATOMS_E2E_ORG_ID: ${{ secrets.ATOMS_E2E_ORG_ID }}
  ATOMS_E2E_OAUTH_CLIENT_ID_BOOKER_EMBED: ${{ secrets.ATOMS_E2E_OAUTH_CLIENT_ID_BOOKER_EMBED }}

jobs:
  e2e:
    timeout-minutes: ${{ inputs.timeout_minutes }}
    name: E2E ${{ inputs.test_type }}${{ matrix.shard && format(' ({0}/{1})', matrix.shard, strategy.job-total) || '' }}
    runs-on: ${{ inputs.runner_spec }}
    services:
      postgres:
        image: postgres:13
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: calendso
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mailhog:
        image: mailhog/mailhog:v1.0.1
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        ports:
          - 8025:8025
          - 1025:1025
      redis:
        image: redis:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(inputs.matrix_shards) }}
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/yarn-playwright-install
        if: ${{ inputs.test_type != 'api-v2' }}
      - uses: ./.github/actions/cache-db
        if: ${{ inputs.test_type != 'atoms' }}
        env:
          DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
          DATABASE_DIRECT_URL: ${{ secrets.CI_DATABASE_URL }}
          E2E_TEST_CALCOM_QA_EMAIL: ${{ secrets.E2E_TEST_CALCOM_QA_EMAIL }}
          E2E_TEST_CALCOM_QA_PASSWORD: ${{ secrets.E2E_TEST_CALCOM_QA_PASSWORD }}
          E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS: ${{ secrets.E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS }}
          E2E_TEST_CALCOM_GCAL_KEYS: ${{ secrets.E2E_TEST_CALCOM_GCAL_KEYS }}
      - uses: ./.github/actions/cache-build
        if: ${{ inputs.test_type != 'api-v2' && inputs.test_type != 'atoms' }}
      - name: Run Tests
        run: |
          case "${{ inputs.test_type }}" in
            "core")
              yarn e2e --shard=${{ matrix.shard }}/${{ strategy.job-total }}
              ;;
            "embed")
              yarn e2e:embed
              ;;
            "app-store")
              yarn e2e:app-store
              ;;
            "embed-react")
              yarn e2e:embed-react
              yarn workspace @calcom/embed-react packaged:tests
              ;;
            "api-v2")
              cd apps/api/v2
              yarn test:e2e
              EXIT_CODE=$?
              echo "yarn test:e2e command exit code: $EXIT_CODE"
              exit $EXIT_CODE
              ;;
            "atoms")
              cd packages/platform/examples/base
              yarn test:e2e
              ;;
            *)
              echo "Unknown test type: ${{ inputs.test_type }}"
              exit 1
              ;;
          esac
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.test_type == 'core' && format('blob-report-{0}', matrix.shard) || inputs.test_type == 'api-v2' && 'test-results-api-v2' || format('blob-report-{0}', inputs.test_type) }}
          path: ${{ inputs.test_type == 'atoms' && 'test-results' || inputs.test_type == 'api-v2' && 'test-results' || 'blob-report' }}
          retention-days: ${{ inputs.test_type == 'atoms' && 7 || 30 }}
      - name: Upload Playwright Report (Atoms only)
        uses: actions/upload-artifact@v4
        if: always() && inputs.test_type == 'atoms'
        with:
          name: e2e-atoms-playwright-report
          path: playwright-report
          retention-days: 7
