name: PR Label Check
on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
      - gh-actions-test-branch

permissions:
  actions: write
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  call-pr-update:
    if: ${{ github.event.label.name == 'ready-for-e2e' }}
    uses: ./.github/workflows/pr.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_sha: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
