name: Unit
on:
  workflow_call:
env:
  LINGO_DOT_DEV_API_KEY: ${{ secrets.CI_LINGO_DOT_DEV_API_KEY }}
permissions:
  contents: read
jobs:
  test:
    name: Unit
    timeout-minutes: 20
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - run: yarn test:coverage -- --no-isolate
      # We could add different timezones here that we need to run our tests in
      - run: TZ=America/Los_Angeles yarn test:coverage -- --timeZoneDependentTestsOnly --no-isolate
      - name: Run API v2 tests with coverage
        working-directory: apps/api/v2
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn test:cov
      - name: Check coverage thresholds
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            node -e "
              const coverage = require('./coverage/coverage-summary.json');
              const { lines, branches, functions, statements } = coverage.total;
              console.log('Coverage Summary:');
              console.log('Lines:', lines.pct + '%');
              console.log('Branches:', branches.pct + '%');
              console.log('Functions:', functions.pct + '%');
              console.log('Statements:', statements.pct + '%');
              
              if (lines.pct < 1 || branches.pct < 1 || functions.pct < 1 || statements.pct < 1) {
                console.error('Coverage thresholds not met!');
                process.exit(1);
              }
              console.log('All coverage thresholds met!');
            "
          else
            echo 'No coverage summary found'
            exit 1
          fi
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            coverage/
            apps/api/v2/coverage/
          retention-days: 30
